using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges.Messenger;

[GenerateTypedNameReferences]
public sealed partial class MessengerUiChatItem : BoxContainer
{
    public MessengerUiChatItem()
    {
        RobustXamlLoader.Load(this);
    }
}
