using Content.Shared.CartridgeLoader.Cartridges;
using Content.Shared.MessengerCartridge;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.MessengerCartridge;

[GenerateTypedNameReferences]
public sealed partial class MessengerCartridgeUiChatItem : BoxContainer
{
    public MessengerCartridgeUiChatItem()
    {
        RobustXamlLoader.Load(this);
    }
}
